
package com.avaya.pim.services.pomcmpmgmtservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:15:55.881+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "GetActiveJobTaskIdsFaultInfo", targetNamespace = "http://services.pim.avaya.com/CmpMgmt/")
public class GetActiveJobTaskIdsFault extends Exception {
    
    private com.avaya.pim.services.pomcmpmgmtservice.GetActiveJobTaskIdsFaultInfo getActiveJobTaskIdsFaultInfo;

    public GetActiveJobTaskIdsFault() {
        super();
    }
    
    public GetActiveJobTaskIdsFault(String message) {
        super(message);
    }
    
    public GetActiveJobTaskIdsFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetActiveJobTaskIdsFault(String message, com.avaya.pim.services.pomcmpmgmtservice.GetActiveJobTaskIdsFaultInfo getActiveJobTaskIdsFaultInfo) {
        super(message);
        this.getActiveJobTaskIdsFaultInfo = getActiveJobTaskIdsFaultInfo;
    }

    public GetActiveJobTaskIdsFault(String message, com.avaya.pim.services.pomcmpmgmtservice.GetActiveJobTaskIdsFaultInfo getActiveJobTaskIdsFaultInfo, Throwable cause) {
        super(message, cause);
        this.getActiveJobTaskIdsFaultInfo = getActiveJobTaskIdsFaultInfo;
    }

    public com.avaya.pim.services.pomcmpmgmtservice.GetActiveJobTaskIdsFaultInfo getFaultInfo() {
        return this.getActiveJobTaskIdsFaultInfo;
    }
}
