
package com.avaya.pim.services.pomcmpmgmtservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:15:56.032+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "GetActiveJobTaskIdForTaskFaultInfo", targetNamespace = "http://services.pim.avaya.com/CmpMgmt/")
public class GetActiveJobTaskIdForTaskFault extends Exception {
    
    private com.avaya.pim.services.pomcmpmgmtservice.GetActiveJobTaskIdForTaskFaultInfo getActiveJobTaskIdForTaskFaultInfo;

    public GetActiveJobTaskIdForTaskFault() {
        super();
    }
    
    public GetActiveJobTaskIdForTaskFault(String message) {
        super(message);
    }
    
    public GetActiveJobTaskIdForTaskFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetActiveJobTaskIdForTaskFault(String message, com.avaya.pim.services.pomcmpmgmtservice.GetActiveJobTaskIdForTaskFaultInfo getActiveJobTaskIdForTaskFaultInfo) {
        super(message);
        this.getActiveJobTaskIdForTaskFaultInfo = getActiveJobTaskIdForTaskFaultInfo;
    }

    public GetActiveJobTaskIdForTaskFault(String message, com.avaya.pim.services.pomcmpmgmtservice.GetActiveJobTaskIdForTaskFaultInfo getActiveJobTaskIdForTaskFaultInfo, Throwable cause) {
        super(message, cause);
        this.getActiveJobTaskIdForTaskFaultInfo = getActiveJobTaskIdForTaskFaultInfo;
    }

    public com.avaya.pim.services.pomcmpmgmtservice.GetActiveJobTaskIdForTaskFaultInfo getFaultInfo() {
        return this.getActiveJobTaskIdForTaskFaultInfo;
    }
}
