
package com.avaya.pim.services.pomcmpmgmtservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:15:56.150+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "GetActiveJobsFaultInfo", targetNamespace = "http://services.pim.avaya.com/CmpMgmt/")
public class GetActiveJobsFault extends Exception {
    
    private com.avaya.pim.services.pomcmpmgmtservice.GetActiveJobsFaultInfo getActiveJobsFaultInfo;

    public GetActiveJobsFault() {
        super();
    }
    
    public GetActiveJobsFault(String message) {
        super(message);
    }
    
    public GetActiveJobsFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetActiveJobsFault(String message, com.avaya.pim.services.pomcmpmgmtservice.GetActiveJobsFaultInfo getActiveJobsFaultInfo) {
        super(message);
        this.getActiveJobsFaultInfo = getActiveJobsFaultInfo;
    }

    public GetActiveJobsFault(String message, com.avaya.pim.services.pomcmpmgmtservice.GetActiveJobsFaultInfo getActiveJobsFaultInfo, Throwable cause) {
        super(message, cause);
        this.getActiveJobsFaultInfo = getActiveJobsFaultInfo;
    }

    public com.avaya.pim.services.pomcmpmgmtservice.GetActiveJobsFaultInfo getFaultInfo() {
        return this.getActiveJobsFaultInfo;
    }
}
