
package com.avaya.pim.services.pomcmpmgmtservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:15:56.024+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "GetContactListNamesFaultInfo", targetNamespace = "http://services.pim.avaya.com/CmpMgmt/")
public class GetContactListNamesFault extends Exception {
    
    private com.avaya.pim.services.pomcmpmgmtservice.GetContactListNamesFaultInfo getContactListNamesFaultInfo;

    public GetContactListNamesFault() {
        super();
    }
    
    public GetContactListNamesFault(String message) {
        super(message);
    }
    
    public GetContactListNamesFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetContactListNamesFault(String message, com.avaya.pim.services.pomcmpmgmtservice.GetContactListNamesFaultInfo getContactListNamesFaultInfo) {
        super(message);
        this.getContactListNamesFaultInfo = getContactListNamesFaultInfo;
    }

    public GetContactListNamesFault(String message, com.avaya.pim.services.pomcmpmgmtservice.GetContactListNamesFaultInfo getContactListNamesFaultInfo, Throwable cause) {
        super(message, cause);
        this.getContactListNamesFaultInfo = getContactListNamesFaultInfo;
    }

    public com.avaya.pim.services.pomcmpmgmtservice.GetContactListNamesFaultInfo getFaultInfo() {
        return this.getContactListNamesFaultInfo;
    }
}
