
package com.avaya.pim.services.pomcmpmgmtservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:15:56.088+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "GetCampaignDetailsFaultInfo", targetNamespace = "http://services.pim.avaya.com/CmpMgmt/")
public class GetCampaignDetailsFault extends Exception {
    
    private com.avaya.pim.services.pomcmpmgmtservice.GetCampaignDetailsFaultInfo getCampaignDetailsFaultInfo;

    public GetCampaignDetailsFault() {
        super();
    }
    
    public GetCampaignDetailsFault(String message) {
        super(message);
    }
    
    public GetCampaignDetailsFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetCampaignDetailsFault(String message, com.avaya.pim.services.pomcmpmgmtservice.GetCampaignDetailsFaultInfo getCampaignDetailsFaultInfo) {
        super(message);
        this.getCampaignDetailsFaultInfo = getCampaignDetailsFaultInfo;
    }

    public GetCampaignDetailsFault(String message, com.avaya.pim.services.pomcmpmgmtservice.GetCampaignDetailsFaultInfo getCampaignDetailsFaultInfo, Throwable cause) {
        super(message, cause);
        this.getCampaignDetailsFaultInfo = getCampaignDetailsFaultInfo;
    }

    public com.avaya.pim.services.pomcmpmgmtservice.GetCampaignDetailsFaultInfo getFaultInfo() {
        return this.getCampaignDetailsFaultInfo;
    }
}
