
package com.avaya.pim.services.pomcmpmgmtservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:15:56.080+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "GetCampaignJobsFaultInfo", targetNamespace = "http://services.pim.avaya.com/CmpMgmt/")
public class GetCampaignJobsFault extends Exception {
    
    private com.avaya.pim.services.pomcmpmgmtservice.GetCampaignJobsFaultInfo getCampaignJobsFaultInfo;

    public GetCampaignJobsFault() {
        super();
    }
    
    public GetCampaignJobsFault(String message) {
        super(message);
    }
    
    public GetCampaignJobsFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetCampaignJobsFault(String message, com.avaya.pim.services.pomcmpmgmtservice.GetCampaignJobsFaultInfo getCampaignJobsFaultInfo) {
        super(message);
        this.getCampaignJobsFaultInfo = getCampaignJobsFaultInfo;
    }

    public GetCampaignJobsFault(String message, com.avaya.pim.services.pomcmpmgmtservice.GetCampaignJobsFaultInfo getCampaignJobsFaultInfo, Throwable cause) {
        super(message, cause);
        this.getCampaignJobsFaultInfo = getCampaignJobsFaultInfo;
    }

    public com.avaya.pim.services.pomcmpmgmtservice.GetCampaignJobsFaultInfo getFaultInfo() {
        return this.getCampaignJobsFaultInfo;
    }
}
