
package com.avaya.pim.services.pomcmpmgmtservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:15:56.206+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "GetImportJobStatusFaultInfo", targetNamespace = "http://services.pim.avaya.com/CmpMgmt/")
public class GetImportJobStatusFault extends Exception {
    
    private com.avaya.pim.services.pomcmpmgmtservice.GetImportJobStatusFaultInfo getImportJobStatusFaultInfo;

    public GetImportJobStatusFault() {
        super();
    }
    
    public GetImportJobStatusFault(String message) {
        super(message);
    }
    
    public GetImportJobStatusFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetImportJobStatusFault(String message, com.avaya.pim.services.pomcmpmgmtservice.GetImportJobStatusFaultInfo getImportJobStatusFaultInfo) {
        super(message);
        this.getImportJobStatusFaultInfo = getImportJobStatusFaultInfo;
    }

    public GetImportJobStatusFault(String message, com.avaya.pim.services.pomcmpmgmtservice.GetImportJobStatusFaultInfo getImportJobStatusFaultInfo, Throwable cause) {
        super(message, cause);
        this.getImportJobStatusFaultInfo = getImportJobStatusFaultInfo;
    }

    public com.avaya.pim.services.pomcmpmgmtservice.GetImportJobStatusFaultInfo getFaultInfo() {
        return this.getImportJobStatusFaultInfo;
    }
}
