
package com.avaya.pim.services.pomcmpmgmtservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:15:56.159+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "PauseActiveJobFaultInfo", targetNamespace = "http://services.pim.avaya.com/CmpMgmt/")
public class PauseActiveJobFault extends Exception {
    
    private com.avaya.pim.services.pomcmpmgmtservice.PauseActiveJobFaultInfo pauseActiveJobFaultInfo;

    public PauseActiveJobFault() {
        super();
    }
    
    public PauseActiveJobFault(String message) {
        super(message);
    }
    
    public PauseActiveJobFault(String message, Throwable cause) {
        super(message, cause);
    }

    public PauseActiveJobFault(String message, com.avaya.pim.services.pomcmpmgmtservice.PauseActiveJobFaultInfo pauseActiveJobFaultInfo) {
        super(message);
        this.pauseActiveJobFaultInfo = pauseActiveJobFaultInfo;
    }

    public PauseActiveJobFault(String message, com.avaya.pim.services.pomcmpmgmtservice.PauseActiveJobFaultInfo pauseActiveJobFaultInfo, Throwable cause) {
        super(message, cause);
        this.pauseActiveJobFaultInfo = pauseActiveJobFaultInfo;
    }

    public com.avaya.pim.services.pomcmpmgmtservice.PauseActiveJobFaultInfo getFaultInfo() {
        return this.pauseActiveJobFaultInfo;
    }
}
