
package com.avaya.pim.services.pomcmpmgmtservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:15:55.937+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "RunCampaignFaultInfo", targetNamespace = "http://services.pim.avaya.com/CmpMgmt/")
public class RunCampaignFault extends Exception {
    
    private com.avaya.pim.services.pomcmpmgmtservice.RunCampaignFaultInfo runCampaignFaultInfo;

    public RunCampaignFault() {
        super();
    }
    
    public RunCampaignFault(String message) {
        super(message);
    }
    
    public RunCampaignFault(String message, Throwable cause) {
        super(message, cause);
    }

    public RunCampaignFault(String message, com.avaya.pim.services.pomcmpmgmtservice.RunCampaignFaultInfo runCampaignFaultInfo) {
        super(message);
        this.runCampaignFaultInfo = runCampaignFaultInfo;
    }

    public RunCampaignFault(String message, com.avaya.pim.services.pomcmpmgmtservice.RunCampaignFaultInfo runCampaignFaultInfo, Throwable cause) {
        super(message, cause);
        this.runCampaignFaultInfo = runCampaignFaultInfo;
    }

    public com.avaya.pim.services.pomcmpmgmtservice.RunCampaignFaultInfo getFaultInfo() {
        return this.runCampaignFaultInfo;
    }
}
