
package com.avaya.pim.services.pomcmpmgmtservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:15:55.975+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "ScheduleRecurringDataSourceFaultInfo", targetNamespace = "http://services.pim.avaya.com/CmpMgmt/")
public class ScheduleRecurringDataSourceFault extends Exception {
    
    private com.avaya.pim.services.pomcmpmgmtservice.ScheduleRecurringDataSourceFaultInfo scheduleRecurringDataSourceFaultInfo;

    public ScheduleRecurringDataSourceFault() {
        super();
    }
    
    public ScheduleRecurringDataSourceFault(String message) {
        super(message);
    }
    
    public ScheduleRecurringDataSourceFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ScheduleRecurringDataSourceFault(String message, com.avaya.pim.services.pomcmpmgmtservice.ScheduleRecurringDataSourceFaultInfo scheduleRecurringDataSourceFaultInfo) {
        super(message);
        this.scheduleRecurringDataSourceFaultInfo = scheduleRecurringDataSourceFaultInfo;
    }

    public ScheduleRecurringDataSourceFault(String message, com.avaya.pim.services.pomcmpmgmtservice.ScheduleRecurringDataSourceFaultInfo scheduleRecurringDataSourceFaultInfo, Throwable cause) {
        super(message, cause);
        this.scheduleRecurringDataSourceFaultInfo = scheduleRecurringDataSourceFaultInfo;
    }

    public com.avaya.pim.services.pomcmpmgmtservice.ScheduleRecurringDataSourceFaultInfo getFaultInfo() {
        return this.scheduleRecurringDataSourceFaultInfo;
    }
}
