
package com.avaya.pim.services.pomcmpmgmtservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:15:56.045+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "ScheduleDataSourceFaultInfo", targetNamespace = "http://services.pim.avaya.com/CmpMgmt/")
public class ScheduleDataSourceFault extends Exception {
    
    private com.avaya.pim.services.pomcmpmgmtservice.ScheduleDataSourceFaultInfo scheduleDataSourceFaultInfo;

    public ScheduleDataSourceFault() {
        super();
    }
    
    public ScheduleDataSourceFault(String message) {
        super(message);
    }
    
    public ScheduleDataSourceFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ScheduleDataSourceFault(String message, com.avaya.pim.services.pomcmpmgmtservice.ScheduleDataSourceFaultInfo scheduleDataSourceFaultInfo) {
        super(message);
        this.scheduleDataSourceFaultInfo = scheduleDataSourceFaultInfo;
    }

    public ScheduleDataSourceFault(String message, com.avaya.pim.services.pomcmpmgmtservice.ScheduleDataSourceFaultInfo scheduleDataSourceFaultInfo, Throwable cause) {
        super(message, cause);
        this.scheduleDataSourceFaultInfo = scheduleDataSourceFaultInfo;
    }

    public com.avaya.pim.services.pomcmpmgmtservice.ScheduleDataSourceFaultInfo getFaultInfo() {
        return this.scheduleDataSourceFaultInfo;
    }
}
