
package com.avaya.pim.services.pomcmpmgmtservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:15:56.238+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "ScheduleCampaignFaultInfo", targetNamespace = "http://services.pim.avaya.com/CmpMgmt/")
public class ScheduleCampaignFault extends Exception {
    
    private com.avaya.pim.services.pomcmpmgmtservice.ScheduleCampaignFaultInfo scheduleCampaignFaultInfo;

    public ScheduleCampaignFault() {
        super();
    }
    
    public ScheduleCampaignFault(String message) {
        super(message);
    }
    
    public ScheduleCampaignFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ScheduleCampaignFault(String message, com.avaya.pim.services.pomcmpmgmtservice.ScheduleCampaignFaultInfo scheduleCampaignFaultInfo) {
        super(message);
        this.scheduleCampaignFaultInfo = scheduleCampaignFaultInfo;
    }

    public ScheduleCampaignFault(String message, com.avaya.pim.services.pomcmpmgmtservice.ScheduleCampaignFaultInfo scheduleCampaignFaultInfo, Throwable cause) {
        super(message, cause);
        this.scheduleCampaignFaultInfo = scheduleCampaignFaultInfo;
    }

    public com.avaya.pim.services.pomcmpmgmtservice.ScheduleCampaignFaultInfo getFaultInfo() {
        return this.scheduleCampaignFaultInfo;
    }
}
