
package com.avaya.pim.services.pomcmpmgmtservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:15:56.144+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "SetMaxAttemptsCountForTaskFaultInfo", targetNamespace = "http://services.pim.avaya.com/CmpMgmt/")
public class SetMaxAttemptsCountForTaskFault extends Exception {
    
    private com.avaya.pim.services.pomcmpmgmtservice.SetMaxAttemptsCountForTaskFaultInfo setMaxAttemptsCountForTaskFaultInfo;

    public SetMaxAttemptsCountForTaskFault() {
        super();
    }
    
    public SetMaxAttemptsCountForTaskFault(String message) {
        super(message);
    }
    
    public SetMaxAttemptsCountForTaskFault(String message, Throwable cause) {
        super(message, cause);
    }

    public SetMaxAttemptsCountForTaskFault(String message, com.avaya.pim.services.pomcmpmgmtservice.SetMaxAttemptsCountForTaskFaultInfo setMaxAttemptsCountForTaskFaultInfo) {
        super(message);
        this.setMaxAttemptsCountForTaskFaultInfo = setMaxAttemptsCountForTaskFaultInfo;
    }

    public SetMaxAttemptsCountForTaskFault(String message, com.avaya.pim.services.pomcmpmgmtservice.SetMaxAttemptsCountForTaskFaultInfo setMaxAttemptsCountForTaskFaultInfo, Throwable cause) {
        super(message, cause);
        this.setMaxAttemptsCountForTaskFaultInfo = setMaxAttemptsCountForTaskFaultInfo;
    }

    public com.avaya.pim.services.pomcmpmgmtservice.SetMaxAttemptsCountForTaskFaultInfo getFaultInfo() {
        return this.setMaxAttemptsCountForTaskFaultInfo;
    }
}
