
package com.avaya.pim.services.pomcmpmgmtservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:15:56.187+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "StopJobFaultInfo", targetNamespace = "http://services.pim.avaya.com/CmpMgmt/")
public class StopJobFault extends Exception {
    
    private com.avaya.pim.services.pomcmpmgmtservice.StopJobFaultInfo stopJobFaultInfo;

    public StopJobFault() {
        super();
    }
    
    public StopJobFault(String message) {
        super(message);
    }
    
    public StopJobFault(String message, Throwable cause) {
        super(message, cause);
    }

    public StopJobFault(String message, com.avaya.pim.services.pomcmpmgmtservice.StopJobFaultInfo stopJobFaultInfo) {
        super(message);
        this.stopJobFaultInfo = stopJobFaultInfo;
    }

    public StopJobFault(String message, com.avaya.pim.services.pomcmpmgmtservice.StopJobFaultInfo stopJobFaultInfo, Throwable cause) {
        super(message, cause);
        this.stopJobFaultInfo = stopJobFaultInfo;
    }

    public com.avaya.pim.services.pomcmpmgmtservice.StopJobFaultInfo getFaultInfo() {
        return this.stopJobFaultInfo;
    }
}
