package com.avaya.pim.services.pomcmpmgmtservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:15:56.289+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "VP_POMCmpMgmtService", 
                  wsdlLocation = "file:/C:/Users/cyang/AppData/Local/Temp/tempdir3994968889426754774.tmp/VP_POMCmpMgmtService_1.wsdl",
                  targetNamespace = "http://services.pim.avaya.com/CmpMgmt/") 
public class VPPOMCmpMgmtService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.pim.avaya.com/CmpMgmt/", "VP_POMCmpMgmtService");
    public final static QName CmpMgmtSOAP = new QName("http://services.pim.avaya.com/CmpMgmt/", "CmpMgmtSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/cyang/AppData/Local/Temp/tempdir3994968889426754774.tmp/VP_POMCmpMgmtService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VPPOMCmpMgmtService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/cyang/AppData/Local/Temp/tempdir3994968889426754774.tmp/VP_POMCmpMgmtService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VPPOMCmpMgmtService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VPPOMCmpMgmtService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VPPOMCmpMgmtService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public VPPOMCmpMgmtService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VPPOMCmpMgmtService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VPPOMCmpMgmtService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns VPPOMCmpMgmtService
     */
    @WebEndpoint(name = "CmpMgmtSOAP")
    public VPPOMCmpMgmtService getCmpMgmtSOAP() {
        return super.getPort(CmpMgmtSOAP, VPPOMCmpMgmtService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VPPOMCmpMgmtService
     */
    @WebEndpoint(name = "CmpMgmtSOAP")
    public VPPOMCmpMgmtService getCmpMgmtSOAP(WebServiceFeature... features) {
        return super.getPort(CmpMgmtSOAP, VPPOMCmpMgmtService.class, features);
    }

}
