
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.698+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "AddContactToJobFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class AddContactToJobFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.AddContactToJobFaultInfo addContactToJobFaultInfo;

    public AddContactToJobFault() {
        super();
    }
    
    public AddContactToJobFault(String message) {
        super(message);
    }
    
    public AddContactToJobFault(String message, Throwable cause) {
        super(message, cause);
    }

    public AddContactToJobFault(String message, com.avaya.pim.services.pomagentapiservice.AddContactToJobFaultInfo addContactToJobFaultInfo) {
        super(message);
        this.addContactToJobFaultInfo = addContactToJobFaultInfo;
    }

    public AddContactToJobFault(String message, com.avaya.pim.services.pomagentapiservice.AddContactToJobFaultInfo addContactToJobFaultInfo, Throwable cause) {
        super(message, cause);
        this.addContactToJobFaultInfo = addContactToJobFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.AddContactToJobFaultInfo getFaultInfo() {
        return this.addContactToJobFaultInfo;
    }
}
