
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.781+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "AddContactFromListToJobFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class AddContactFromListToJobFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.AddContactFromListToJobFaultInfo addContactFromListToJobFaultInfo;

    public AddContactFromListToJobFault() {
        super();
    }
    
    public AddContactFromListToJobFault(String message) {
        super(message);
    }
    
    public AddContactFromListToJobFault(String message, Throwable cause) {
        super(message, cause);
    }

    public AddContactFromListToJobFault(String message, com.avaya.pim.services.pomagentapiservice.AddContactFromListToJobFaultInfo addContactFromListToJobFaultInfo) {
        super(message);
        this.addContactFromListToJobFaultInfo = addContactFromListToJobFaultInfo;
    }

    public AddContactFromListToJobFault(String message, com.avaya.pim.services.pomagentapiservice.AddContactFromListToJobFaultInfo addContactFromListToJobFaultInfo, Throwable cause) {
        super(message, cause);
        this.addContactFromListToJobFaultInfo = addContactFromListToJobFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.AddContactFromListToJobFaultInfo getFaultInfo() {
        return this.addContactFromListToJobFaultInfo;
    }
}
