
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.817+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "DeleteContactFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class DeleteContactFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.DeleteContactFaultInfo deleteContactFaultInfo;

    public DeleteContactFault() {
        super();
    }
    
    public DeleteContactFault(String message) {
        super(message);
    }
    
    public DeleteContactFault(String message, Throwable cause) {
        super(message, cause);
    }

    public DeleteContactFault(String message, com.avaya.pim.services.pomagentapiservice.DeleteContactFaultInfo deleteContactFaultInfo) {
        super(message);
        this.deleteContactFaultInfo = deleteContactFaultInfo;
    }

    public DeleteContactFault(String message, com.avaya.pim.services.pomagentapiservice.DeleteContactFaultInfo deleteContactFaultInfo, Throwable cause) {
        super(message, cause);
        this.deleteContactFaultInfo = deleteContactFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.DeleteContactFaultInfo getFaultInfo() {
        return this.deleteContactFaultInfo;
    }
}
