
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.633+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "GetAgentAttributesListFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class GetAgentAttributesListFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.GetAgentAttributesListFaultInfo getAgentAttributesListFaultInfo;

    public GetAgentAttributesListFault() {
        super();
    }
    
    public GetAgentAttributesListFault(String message) {
        super(message);
    }
    
    public GetAgentAttributesListFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAgentAttributesListFault(String message, com.avaya.pim.services.pomagentapiservice.GetAgentAttributesListFaultInfo getAgentAttributesListFaultInfo) {
        super(message);
        this.getAgentAttributesListFaultInfo = getAgentAttributesListFaultInfo;
    }

    public GetAgentAttributesListFault(String message, com.avaya.pim.services.pomagentapiservice.GetAgentAttributesListFaultInfo getAgentAttributesListFaultInfo, Throwable cause) {
        super(message, cause);
        this.getAgentAttributesListFaultInfo = getAgentAttributesListFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.GetAgentAttributesListFaultInfo getFaultInfo() {
        return this.getAgentAttributesListFaultInfo;
    }
}
