
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.670+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "GetAllCompletionCodesForCampaignFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class GetAllCompletionCodesForCampaignFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.GetAllCompletionCodesForCampaignFaultInfo getAllCompletionCodesForCampaignFaultInfo;

    public GetAllCompletionCodesForCampaignFault() {
        super();
    }
    
    public GetAllCompletionCodesForCampaignFault(String message) {
        super(message);
    }
    
    public GetAllCompletionCodesForCampaignFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetAllCompletionCodesForCampaignFault(String message, com.avaya.pim.services.pomagentapiservice.GetAllCompletionCodesForCampaignFaultInfo getAllCompletionCodesForCampaignFaultInfo) {
        super(message);
        this.getAllCompletionCodesForCampaignFaultInfo = getAllCompletionCodesForCampaignFaultInfo;
    }

    public GetAllCompletionCodesForCampaignFault(String message, com.avaya.pim.services.pomagentapiservice.GetAllCompletionCodesForCampaignFaultInfo getAllCompletionCodesForCampaignFaultInfo, Throwable cause) {
        super(message, cause);
        this.getAllCompletionCodesForCampaignFaultInfo = getAllCompletionCodesForCampaignFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.GetAllCompletionCodesForCampaignFaultInfo getFaultInfo() {
        return this.getAllCompletionCodesForCampaignFaultInfo;
    }
}
