
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.824+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "GetContactAttributeValueFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class GetContactAttributeValueFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.GetContactAttributeValueFaultInfo getContactAttributeValueFaultInfo;

    public GetContactAttributeValueFault() {
        super();
    }
    
    public GetContactAttributeValueFault(String message) {
        super(message);
    }
    
    public GetContactAttributeValueFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetContactAttributeValueFault(String message, com.avaya.pim.services.pomagentapiservice.GetContactAttributeValueFaultInfo getContactAttributeValueFaultInfo) {
        super(message);
        this.getContactAttributeValueFaultInfo = getContactAttributeValueFaultInfo;
    }

    public GetContactAttributeValueFault(String message, com.avaya.pim.services.pomagentapiservice.GetContactAttributeValueFaultInfo getContactAttributeValueFaultInfo, Throwable cause) {
        super(message, cause);
        this.getContactAttributeValueFaultInfo = getContactAttributeValueFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.GetContactAttributeValueFaultInfo getFaultInfo() {
        return this.getContactAttributeValueFaultInfo;
    }
}
