
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.813+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "GetContactDataFromListFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class GetContactDataFromListFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.GetContactDataFromListFaultInfo getContactDataFromListFaultInfo;

    public GetContactDataFromListFault() {
        super();
    }
    
    public GetContactDataFromListFault(String message) {
        super(message);
    }
    
    public GetContactDataFromListFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetContactDataFromListFault(String message, com.avaya.pim.services.pomagentapiservice.GetContactDataFromListFaultInfo getContactDataFromListFaultInfo) {
        super(message);
        this.getContactDataFromListFaultInfo = getContactDataFromListFaultInfo;
    }

    public GetContactDataFromListFault(String message, com.avaya.pim.services.pomagentapiservice.GetContactDataFromListFaultInfo getContactDataFromListFaultInfo, Throwable cause) {
        super(message, cause);
        this.getContactDataFromListFaultInfo = getContactDataFromListFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.GetContactDataFromListFaultInfo getFaultInfo() {
        return this.getContactDataFromListFaultInfo;
    }
}
