
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.791+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "GetContactListEmptyStatusFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class GetContactListEmptyStatusFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.GetContactListEmptyStatusFaultInfo getContactListEmptyStatusFaultInfo;

    public GetContactListEmptyStatusFault() {
        super();
    }
    
    public GetContactListEmptyStatusFault(String message) {
        super(message);
    }
    
    public GetContactListEmptyStatusFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetContactListEmptyStatusFault(String message, com.avaya.pim.services.pomagentapiservice.GetContactListEmptyStatusFaultInfo getContactListEmptyStatusFaultInfo) {
        super(message);
        this.getContactListEmptyStatusFaultInfo = getContactListEmptyStatusFaultInfo;
    }

    public GetContactListEmptyStatusFault(String message, com.avaya.pim.services.pomagentapiservice.GetContactListEmptyStatusFaultInfo getContactListEmptyStatusFaultInfo, Throwable cause) {
        super(message, cause);
        this.getContactListEmptyStatusFaultInfo = getContactListEmptyStatusFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.GetContactListEmptyStatusFaultInfo getFaultInfo() {
        return this.getContactListEmptyStatusFaultInfo;
    }
}
