
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.722+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "GetContactAttributeValueFromListFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class GetContactAttributeValueFromListFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.GetContactAttributeValueFromListFaultInfo getContactAttributeValueFromListFaultInfo;

    public GetContactAttributeValueFromListFault() {
        super();
    }
    
    public GetContactAttributeValueFromListFault(String message) {
        super(message);
    }
    
    public GetContactAttributeValueFromListFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetContactAttributeValueFromListFault(String message, com.avaya.pim.services.pomagentapiservice.GetContactAttributeValueFromListFaultInfo getContactAttributeValueFromListFaultInfo) {
        super(message);
        this.getContactAttributeValueFromListFaultInfo = getContactAttributeValueFromListFaultInfo;
    }

    public GetContactAttributeValueFromListFault(String message, com.avaya.pim.services.pomagentapiservice.GetContactAttributeValueFromListFaultInfo getContactAttributeValueFromListFaultInfo, Throwable cause) {
        super(message, cause);
        this.getContactAttributeValueFromListFaultInfo = getContactAttributeValueFromListFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.GetContactAttributeValueFromListFaultInfo getFaultInfo() {
        return this.getContactAttributeValueFromListFaultInfo;
    }
}
