
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.647+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "GetPhoneNumberFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class GetPhoneNumberFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.GetPhoneNumberFaultInfo getPhoneNumberFaultInfo;

    public GetPhoneNumberFault() {
        super();
    }
    
    public GetPhoneNumberFault(String message) {
        super(message);
    }
    
    public GetPhoneNumberFault(String message, Throwable cause) {
        super(message, cause);
    }

    public GetPhoneNumberFault(String message, com.avaya.pim.services.pomagentapiservice.GetPhoneNumberFaultInfo getPhoneNumberFaultInfo) {
        super(message);
        this.getPhoneNumberFaultInfo = getPhoneNumberFaultInfo;
    }

    public GetPhoneNumberFault(String message, com.avaya.pim.services.pomagentapiservice.GetPhoneNumberFaultInfo getPhoneNumberFaultInfo, Throwable cause) {
        super(message, cause);
        this.getPhoneNumberFaultInfo = getPhoneNumberFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.GetPhoneNumberFaultInfo getFaultInfo() {
        return this.getPhoneNumberFaultInfo;
    }
}
