
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.873+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "RemoveFromDNCListFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class RemoveFromDNCListFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.RemoveFromDNCListFaultInfo removeFromDNCListFaultInfo;

    public RemoveFromDNCListFault() {
        super();
    }
    
    public RemoveFromDNCListFault(String message) {
        super(message);
    }
    
    public RemoveFromDNCListFault(String message, Throwable cause) {
        super(message, cause);
    }

    public RemoveFromDNCListFault(String message, com.avaya.pim.services.pomagentapiservice.RemoveFromDNCListFaultInfo removeFromDNCListFaultInfo) {
        super(message);
        this.removeFromDNCListFaultInfo = removeFromDNCListFaultInfo;
    }

    public RemoveFromDNCListFault(String message, com.avaya.pim.services.pomagentapiservice.RemoveFromDNCListFaultInfo removeFromDNCListFaultInfo, Throwable cause) {
        super(message, cause);
        this.removeFromDNCListFaultInfo = removeFromDNCListFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.RemoveFromDNCListFaultInfo getFaultInfo() {
        return this.removeFromDNCListFaultInfo;
    }
}
