
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.545+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "SaveContactToListFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class SaveContactToListFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.SaveContactToListFaultInfo saveContactToListFaultInfo;

    public SaveContactToListFault() {
        super();
    }
    
    public SaveContactToListFault(String message) {
        super(message);
    }
    
    public SaveContactToListFault(String message, Throwable cause) {
        super(message, cause);
    }

    public SaveContactToListFault(String message, com.avaya.pim.services.pomagentapiservice.SaveContactToListFaultInfo saveContactToListFaultInfo) {
        super(message);
        this.saveContactToListFaultInfo = saveContactToListFaultInfo;
    }

    public SaveContactToListFault(String message, com.avaya.pim.services.pomagentapiservice.SaveContactToListFaultInfo saveContactToListFaultInfo, Throwable cause) {
        super(message, cause);
        this.saveContactToListFaultInfo = saveContactToListFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.SaveContactToListFaultInfo getFaultInfo() {
        return this.saveContactToListFaultInfo;
    }
}
