
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.835+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "ScheduleCallBackFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class ScheduleCallBackFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.ScheduleCallBackFaultInfo scheduleCallBackFaultInfo;

    public ScheduleCallBackFault() {
        super();
    }
    
    public ScheduleCallBackFault(String message) {
        super(message);
    }
    
    public ScheduleCallBackFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ScheduleCallBackFault(String message, com.avaya.pim.services.pomagentapiservice.ScheduleCallBackFaultInfo scheduleCallBackFaultInfo) {
        super(message);
        this.scheduleCallBackFaultInfo = scheduleCallBackFaultInfo;
    }

    public ScheduleCallBackFault(String message, com.avaya.pim.services.pomagentapiservice.ScheduleCallBackFaultInfo scheduleCallBackFaultInfo, Throwable cause) {
        super(message, cause);
        this.scheduleCallBackFaultInfo = scheduleCallBackFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.ScheduleCallBackFaultInfo getFaultInfo() {
        return this.scheduleCallBackFaultInfo;
    }
}
