
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.502+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "UpdatePhoneNumberFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class UpdatePhoneNumberFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.UpdatePhoneNumberFaultInfo updatePhoneNumberFaultInfo;

    public UpdatePhoneNumberFault() {
        super();
    }
    
    public UpdatePhoneNumberFault(String message) {
        super(message);
    }
    
    public UpdatePhoneNumberFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UpdatePhoneNumberFault(String message, com.avaya.pim.services.pomagentapiservice.UpdatePhoneNumberFaultInfo updatePhoneNumberFaultInfo) {
        super(message);
        this.updatePhoneNumberFaultInfo = updatePhoneNumberFaultInfo;
    }

    public UpdatePhoneNumberFault(String message, com.avaya.pim.services.pomagentapiservice.UpdatePhoneNumberFaultInfo updatePhoneNumberFaultInfo, Throwable cause) {
        super(message, cause);
        this.updatePhoneNumberFaultInfo = updatePhoneNumberFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.UpdatePhoneNumberFaultInfo getFaultInfo() {
        return this.updatePhoneNumberFaultInfo;
    }
}
