
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.861+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "UpdateAgentAttributeValueFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class UpdateAgentAttributeValueFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.UpdateAgentAttributeValueFaultInfo updateAgentAttributeValueFaultInfo;

    public UpdateAgentAttributeValueFault() {
        super();
    }
    
    public UpdateAgentAttributeValueFault(String message) {
        super(message);
    }
    
    public UpdateAgentAttributeValueFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UpdateAgentAttributeValueFault(String message, com.avaya.pim.services.pomagentapiservice.UpdateAgentAttributeValueFaultInfo updateAgentAttributeValueFaultInfo) {
        super(message);
        this.updateAgentAttributeValueFaultInfo = updateAgentAttributeValueFaultInfo;
    }

    public UpdateAgentAttributeValueFault(String message, com.avaya.pim.services.pomagentapiservice.UpdateAgentAttributeValueFaultInfo updateAgentAttributeValueFaultInfo, Throwable cause) {
        super(message, cause);
        this.updateAgentAttributeValueFaultInfo = updateAgentAttributeValueFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.UpdateAgentAttributeValueFaultInfo getFaultInfo() {
        return this.updateAgentAttributeValueFaultInfo;
    }
}
