
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.879+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "UpdateCampaignAttributeValueFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class UpdateCampaignAttributeValueFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.UpdateCampaignAttributeValueFaultInfo updateCampaignAttributeValueFaultInfo;

    public UpdateCampaignAttributeValueFault() {
        super();
    }
    
    public UpdateCampaignAttributeValueFault(String message) {
        super(message);
    }
    
    public UpdateCampaignAttributeValueFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UpdateCampaignAttributeValueFault(String message, com.avaya.pim.services.pomagentapiservice.UpdateCampaignAttributeValueFaultInfo updateCampaignAttributeValueFaultInfo) {
        super(message);
        this.updateCampaignAttributeValueFaultInfo = updateCampaignAttributeValueFaultInfo;
    }

    public UpdateCampaignAttributeValueFault(String message, com.avaya.pim.services.pomagentapiservice.UpdateCampaignAttributeValueFaultInfo updateCampaignAttributeValueFaultInfo, Throwable cause) {
        super(message, cause);
        this.updateCampaignAttributeValueFaultInfo = updateCampaignAttributeValueFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.UpdateCampaignAttributeValueFaultInfo getFaultInfo() {
        return this.updateCampaignAttributeValueFaultInfo;
    }
}
