
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.807+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "UpdateContactAttributeValueFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class UpdateContactAttributeValueFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.UpdateContactAttributeValueFaultInfo updateContactAttributeValueFaultInfo;

    public UpdateContactAttributeValueFault() {
        super();
    }
    
    public UpdateContactAttributeValueFault(String message) {
        super(message);
    }
    
    public UpdateContactAttributeValueFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UpdateContactAttributeValueFault(String message, com.avaya.pim.services.pomagentapiservice.UpdateContactAttributeValueFaultInfo updateContactAttributeValueFaultInfo) {
        super(message);
        this.updateContactAttributeValueFaultInfo = updateContactAttributeValueFaultInfo;
    }

    public UpdateContactAttributeValueFault(String message, com.avaya.pim.services.pomagentapiservice.UpdateContactAttributeValueFaultInfo updateContactAttributeValueFaultInfo, Throwable cause) {
        super(message, cause);
        this.updateContactAttributeValueFaultInfo = updateContactAttributeValueFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.UpdateContactAttributeValueFaultInfo getFaultInfo() {
        return this.updateContactAttributeValueFaultInfo;
    }
}
