
package com.avaya.pim.services.pomagentapiservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.486+08:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "UpdateCompletionCodeFaultInfo", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
public class UpdateCompletionCodeFault extends Exception {
    
    private com.avaya.pim.services.pomagentapiservice.UpdateCompletionCodeFaultInfo updateCompletionCodeFaultInfo;

    public UpdateCompletionCodeFault() {
        super();
    }
    
    public UpdateCompletionCodeFault(String message) {
        super(message);
    }
    
    public UpdateCompletionCodeFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UpdateCompletionCodeFault(String message, com.avaya.pim.services.pomagentapiservice.UpdateCompletionCodeFaultInfo updateCompletionCodeFaultInfo) {
        super(message);
        this.updateCompletionCodeFaultInfo = updateCompletionCodeFaultInfo;
    }

    public UpdateCompletionCodeFault(String message, com.avaya.pim.services.pomagentapiservice.UpdateCompletionCodeFaultInfo updateCompletionCodeFaultInfo, Throwable cause) {
        super(message, cause);
        this.updateCompletionCodeFaultInfo = updateCompletionCodeFaultInfo;
    }

    public com.avaya.pim.services.pomagentapiservice.UpdateCompletionCodeFaultInfo getFaultInfo() {
        return this.updateCompletionCodeFaultInfo;
    }
}
