package com.avaya.pim.services.pomagentapiservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.981+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "VP_POMAgentAPIService", 
                  wsdlLocation = "file:/C:/Users/cyang/AppData/Local/Temp/tempdir8730355702873473863.tmp/VP_POMAgentAPIService_1.wsdl",
                  targetNamespace = "http://services.pim.avaya.com/AgentAPI/") 
public class VPPOMAgentAPIService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.pim.avaya.com/AgentAPI/", "VP_POMAgentAPIService");
    public final static QName AgentAPISOAP = new QName("http://services.pim.avaya.com/AgentAPI/", "AgentAPISOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/cyang/AppData/Local/Temp/tempdir8730355702873473863.tmp/VP_POMAgentAPIService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VPPOMAgentAPIService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/cyang/AppData/Local/Temp/tempdir8730355702873473863.tmp/VP_POMAgentAPIService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VPPOMAgentAPIService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VPPOMAgentAPIService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VPPOMAgentAPIService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public VPPOMAgentAPIService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VPPOMAgentAPIService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VPPOMAgentAPIService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns VPPOMAgentAPIService
     */
    @WebEndpoint(name = "AgentAPISOAP")
    public VPPOMAgentAPIService getAgentAPISOAP() {
        return super.getPort(AgentAPISOAP, VPPOMAgentAPIService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VPPOMAgentAPIService
     */
    @WebEndpoint(name = "AgentAPISOAP")
    public VPPOMAgentAPIService getAgentAPISOAP(WebServiceFeature... features) {
        return super.getPort(AgentAPISOAP, VPPOMAgentAPIService.class, features);
    }

}
