package com.avaya.pim.services.pomagentapiservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-07-14T11:11:51.883+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://services.pim.avaya.com/AgentAPI/", name = "VP_POMAgentAPIService")
@XmlSeeAlso({ObjectFactory.class})
public interface VPPOMAgentAPIService {

    @WebMethod(operationName = "GetContactData", action = "http://services.pim.avaya.com/AgentAPI/GetContactData")
    @RequestWrapper(localName = "GetContactData", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetContactData")
    @ResponseWrapper(localName = "GetContactDataResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetContactDataResponse")
    @WebResult(name = "Contact", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public com.avaya.pim.services.pomagentapiservice.ContactType getContactData(
        @WebParam(name = "ContactID", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactID,
        @WebParam(name = "ContactGroupName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactGroupName
    ) throws GetContactDataFault;

    @WebMethod(operationName = "GetAttributesList", action = "http://services.pim.avaya.com/AgentAPI/GetAttributesList")
    @RequestWrapper(localName = "GetAttributesList", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetAttributesList")
    @ResponseWrapper(localName = "GetAttributesListResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetAttributesListResponse")
    @WebResult(name = "attributes", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public java.util.List<com.avaya.pim.services.pomagentapiservice.AttributeType> getAttributesList(
        @WebParam(name = "ContactListName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactListName
    ) throws GetAttributesListFault;

    @WebMethod(operationName = "UpdateCompletionCode", action = "http://services.pim.avaya.com/AgentAPI/UpdateCompletionCode")
    @RequestWrapper(localName = "UpdateCompletionCode", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.UpdateCompletionCode")
    @ResponseWrapper(localName = "UpdateCompletionCodeResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.UpdateCompletionCodeResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public int updateCompletionCode(
        @WebParam(name = "PimSessionID", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        double pimSessionID,
        @WebParam(name = "CompletionCode", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String completionCode
    ) throws UpdateCompletionCodeFault;

    @WebMethod(operationName = "IsDNC", action = "http://services.pim.avaya.com/AgentAPI/IsDNC")
    @RequestWrapper(localName = "IsDNC", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.IsDNC")
    @ResponseWrapper(localName = "IsDNCResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.IsDNCResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public boolean isDNC(
        @WebParam(name = "Address", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String address,
        @WebParam(name = "OrgName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String orgName,
        @WebParam(name = "CheckForRejectPattern", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.Boolean checkForRejectPattern,
        @WebParam(name = "CheckForPhoneFormatsRule", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.Boolean checkForPhoneFormatsRule
    ) throws IsDNCFault;

    @WebMethod(operationName = "UpdatePhoneNumber", action = "http://services.pim.avaya.com/AgentAPI/UpdatePhoneNumber")
    @RequestWrapper(localName = "UpdatePhoneNumber", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.UpdatePhoneNumber")
    @ResponseWrapper(localName = "UpdatePhoneNumberResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.UpdatePhoneNumberResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public int updatePhoneNumber(
        @WebParam(name = "ContactID", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactID,
        @WebParam(name = "ContactListName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactListName,
        @WebParam(name = "PhoneObject", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        com.avaya.pim.services.pomagentapiservice.PhoneType phoneObject,
        @WebParam(name = "AutomaticUpdateForTimeZone", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.Boolean automaticUpdateForTimeZone,
        @WebParam(name = "CheckForRejectPattern", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.Boolean checkForRejectPattern,
        @WebParam(name = "CheckForPhoneFormatsRule", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.Boolean checkForPhoneFormatsRule,
        @WebParam(name = "CheckDNC", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.Boolean checkDNC
    ) throws UpdatePhoneNumberFault;

    @WebMethod(operationName = "DeleteContactFromList", action = "http://services.pim.avaya.com/AgentAPI/DeleteContactFromList")
    @RequestWrapper(localName = "DeleteContactFromList", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.DeleteContactFromList")
    @ResponseWrapper(localName = "DeleteContactFromListResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.DeleteContactFromListResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public boolean deleteContactFromList(
        @WebParam(name = "ContactID", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactID,
        @WebParam(name = "ContactListName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactListName
    ) throws DeleteContactFromListFault;

    @WebMethod(operationName = "AddToDNCList", action = "http://services.pim.avaya.com/AgentAPI/AddToDNCList")
    @RequestWrapper(localName = "AddToDNCList", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.AddToDNCList")
    @ResponseWrapper(localName = "AddToDNCListResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.AddToDNCListResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public boolean addToDNCList(
        @WebParam(name = "Address", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String address,
        @WebParam(name = "OrgName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String orgName,
        @WebParam(name = "CheckForRejectPattern", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.Boolean checkForRejectPattern,
        @WebParam(name = "CheckForPhoneFormatsRule", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.Boolean checkForPhoneFormatsRule
    ) throws AddToDNCListFault;

    @WebMethod(operationName = "SaveContactToList", action = "http://services.pim.avaya.com/AgentAPI/SaveContactToList")
    @RequestWrapper(localName = "SaveContactToList", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.SaveContactToList")
    @ResponseWrapper(localName = "SaveContactToListResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.SaveContactToListResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public int saveContactToList(
        @WebParam(name = "ContactToBeSaved", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        com.avaya.pim.services.pomagentapiservice.ContactDataType contactToBeSaved,
        @WebParam(name = "AutomaticUpdateForTimeZone", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.Boolean automaticUpdateForTimeZone,
        @WebParam(name = "CheckForRejectPattern", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.Boolean checkForRejectPattern,
        @WebParam(name = "CheckForPhoneFormatsRule", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.Boolean checkForPhoneFormatsRule,
        @WebParam(name = "UpdateExisting", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.Boolean updateExisting,
        @WebParam(name = "CheckDNC", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.Boolean checkDNC
    ) throws SaveContactToListFault;

    @WebMethod(operationName = "AddContactListToJob", action = "http://services.pim.avaya.com/AgentAPI/AddContactListToJob")
    @RequestWrapper(localName = "AddContactListToJob", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.AddContactListToJob")
    @ResponseWrapper(localName = "AddContactListToJobResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.AddContactListToJobResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public int addContactListToJob(
        @WebParam(name = "CampaignName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String campaignName,
        @WebParam(name = "ContactListName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactListName,
        @WebParam(name = "ContactPriority", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        com.avaya.pim.services.pomagentapiservice.Priority contactPriority,
        @WebParam(name = "ApplyFilter", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.Boolean applyFilter
    ) throws AddContactListToJobFault;

    @WebMethod(operationName = "GetAgentAttributesList", action = "http://services.pim.avaya.com/AgentAPI/GetAgentAttributesList")
    @RequestWrapper(localName = "GetAgentAttributesList", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetAgentAttributesList")
    @ResponseWrapper(localName = "GetAgentAttributesListResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetAgentAttributesListResponse")
    @WebResult(name = "agentAttributes", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public java.util.List<com.avaya.pim.services.pomagentapiservice.AttributeType> getAgentAttributesList() throws GetAgentAttributesListFault;

    @WebMethod(operationName = "GetPhoneNumber", action = "http://services.pim.avaya.com/AgentAPI/GetPhoneNumber")
    @RequestWrapper(localName = "GetPhoneNumber", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetPhoneNumber")
    @ResponseWrapper(localName = "GetPhoneNumberResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetPhoneNumberResponse")
    @WebResult(name = "Phone", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public com.avaya.pim.services.pomagentapiservice.PhoneType getPhoneNumber(
        @WebParam(name = "ContactID", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactID,
        @WebParam(name = "ContactListName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactListName,
        @WebParam(name = "PhoneAttributeName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String phoneAttributeName
    ) throws GetPhoneNumberFault;

    @WebMethod(operationName = "EmptyContactList", action = "http://services.pim.avaya.com/AgentAPI/EmptyContactList")
    @RequestWrapper(localName = "EmptyContactList", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.EmptyContactList")
    @ResponseWrapper(localName = "EmptyContactListResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.EmptyContactListResponse")
    @WebResult(name = "TotalContacts", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public long emptyContactList(
        @WebParam(name = "ContactListName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactListName
    ) throws EmptyContactListFault;

    @WebMethod(operationName = "GetAllCompletionCodesForCampaign", action = "http://services.pim.avaya.com/AgentAPI/GetAllCompletionCodesForCampaign")
    @RequestWrapper(localName = "GetAllCompletionCodesForCampaign", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetAllCompletionCodesForCampaign")
    @ResponseWrapper(localName = "GetAllCompletionCodesForCampaignResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetAllCompletionCodesForCampaignResponse")
    @WebResult(name = "CompletionCodes", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public java.util.List<java.lang.String> getAllCompletionCodesForCampaign(
        @WebParam(name = "JobID", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        int jobID
    ) throws GetAllCompletionCodesForCampaignFault;

    @WebMethod(operationName = "AddContactToJob", action = "http://services.pim.avaya.com/AgentAPI/AddContactToJob")
    @RequestWrapper(localName = "AddContactToJob", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.AddContactToJob")
    @ResponseWrapper(localName = "AddContactToJobResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.AddContactToJobResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public int addContactToJob(
        @WebParam(name = "CampaignName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String campaignName,
        @WebParam(name = "ContactID", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactID,
        @WebParam(name = "ContactGroupName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactGroupName
    ) throws AddContactToJobFault;

    @WebMethod(operationName = "GetContactAttributeValueFromList", action = "http://services.pim.avaya.com/AgentAPI/GetContactAttributeValueFromList")
    @RequestWrapper(localName = "GetContactAttributeValueFromList", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetContactAttributeValueFromList")
    @ResponseWrapper(localName = "GetContactAttributeValueFromListResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetContactAttributeValueFromListResponse")
    @WebResult(name = "AttributeValue", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public java.lang.String getContactAttributeValueFromList(
        @WebParam(name = "ContactID", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactID,
        @WebParam(name = "ContactListName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactListName,
        @WebParam(name = "AttributeName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String attributeName
    ) throws GetContactAttributeValueFromListFault;

    @WebMethod(operationName = "SaveContact", action = "http://services.pim.avaya.com/AgentAPI/SaveContact")
    @RequestWrapper(localName = "SaveContact", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.SaveContact")
    @ResponseWrapper(localName = "SaveContactResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.SaveContactResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public int saveContact(
        @WebParam(name = "Contact", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        com.avaya.pim.services.pomagentapiservice.ContactType contact
    ) throws SaveContactFault;

    @WebMethod(operationName = "AddContactFromListToJob", action = "http://services.pim.avaya.com/AgentAPI/AddContactFromListToJob")
    @RequestWrapper(localName = "AddContactFromListToJob", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.AddContactFromListToJob")
    @ResponseWrapper(localName = "AddContactFromListToJobResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.AddContactFromListToJobResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public int addContactFromListToJob(
        @WebParam(name = "CampaignName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String campaignName,
        @WebParam(name = "ContactID", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactID,
        @WebParam(name = "ContactListName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactListName,
        @WebParam(name = "ContactPriority", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        com.avaya.pim.services.pomagentapiservice.Priority contactPriority
    ) throws AddContactFromListToJobFault;

    @WebMethod(operationName = "GetContactListEmptyStatus", action = "http://services.pim.avaya.com/AgentAPI/GetContactListEmptyStatus")
    @RequestWrapper(localName = "GetContactListEmptyStatus", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetContactListEmptyStatus")
    @ResponseWrapper(localName = "GetContactListEmptyStatusResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetContactListEmptyStatusResponse")
    @WebResult(name = "ContactListEmptyStatus", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public com.avaya.pim.services.pomagentapiservice.ContactListStatus getContactListEmptyStatus(
        @WebParam(name = "ContactListName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactListName
    ) throws GetContactListEmptyStatusFault;

    @WebMethod(operationName = "UpdateContactAttributeValue", action = "http://services.pim.avaya.com/AgentAPI/UpdateContactAttributeValue")
    @RequestWrapper(localName = "UpdateContactAttributeValue", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.UpdateContactAttributeValue")
    @ResponseWrapper(localName = "UpdateContactAttributeValueResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.UpdateContactAttributeValueResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public int updateContactAttributeValue(
        @WebParam(name = "ContactID", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactID,
        @WebParam(name = "ContactGroupName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactGroupName,
        @WebParam(name = "AttributeName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String attributeName,
        @WebParam(name = "AttributeValue", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String attributeValue
    ) throws UpdateContactAttributeValueFault;

    @WebMethod(operationName = "GetContactDataFromList", action = "http://services.pim.avaya.com/AgentAPI/GetContactDataFromList")
    @RequestWrapper(localName = "GetContactDataFromList", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetContactDataFromList")
    @ResponseWrapper(localName = "GetContactDataFromListResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetContactDataFromListResponse")
    @WebResult(name = "ContactRecord", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public com.avaya.pim.services.pomagentapiservice.ContactDataType getContactDataFromList(
        @WebParam(name = "UserContactID", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String userContactID,
        @WebParam(name = "ContactListName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactListName
    ) throws GetContactDataFromListFault;

    @WebMethod(operationName = "DeleteContact", action = "http://services.pim.avaya.com/AgentAPI/DeleteContact")
    @RequestWrapper(localName = "DeleteContact", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.DeleteContact")
    @ResponseWrapper(localName = "DeleteContactResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.DeleteContactResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public boolean deleteContact(
        @WebParam(name = "ContactID", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactID,
        @WebParam(name = "ContactGroupName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactGroupName
    ) throws DeleteContactFault;

    @WebMethod(operationName = "GetContactAttributeValue", action = "http://services.pim.avaya.com/AgentAPI/GetContactAttributeValue")
    @RequestWrapper(localName = "GetContactAttributeValue", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetContactAttributeValue")
    @ResponseWrapper(localName = "GetContactAttributeValueResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetContactAttributeValueResponse")
    @WebResult(name = "AttributeValue", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public java.lang.String getContactAttributeValue(
        @WebParam(name = "ContactID", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactID,
        @WebParam(name = "ContactGroupName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactGroupName,
        @WebParam(name = "AttributeName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String attributeName
    ) throws GetContactAttributeValueFault;

    @WebMethod(operationName = "AddContactGroupToJob", action = "http://services.pim.avaya.com/AgentAPI/AddContactGroupToJob")
    @RequestWrapper(localName = "AddContactGroupToJob", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.AddContactGroupToJob")
    @ResponseWrapper(localName = "AddContactGroupToJobResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.AddContactGroupToJobResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public int addContactGroupToJob(
        @WebParam(name = "CampaignName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String campaignName,
        @WebParam(name = "ContactGroupName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactGroupName
    ) throws AddContactGroupToJobFault;

    @WebMethod(operationName = "ScheduleCallBack", action = "http://services.pim.avaya.com/AgentAPI/ScheduleCallBack")
    @RequestWrapper(localName = "ScheduleCallBack", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.ScheduleCallBack")
    @ResponseWrapper(localName = "ScheduleCallBackResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.ScheduleCallBackResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public int scheduleCallBack(
        @WebParam(name = "UserContactID", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String userContactID,
        @WebParam(name = "ContactListName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactListName,
        @WebParam(name = "CampaignName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String campaignName,
        @WebParam(name = "StartTime", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String endTime,
        @WebParam(name = "TimeZone", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String timeZone,
        @WebParam(name = "ContactAttributeName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactAttributeName,
        @WebParam(name = "Address", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String address,
        @WebParam(name = "Notes", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String notes
    ) throws ScheduleCallBackFault;

    @WebMethod(operationName = "UpdateAgentAttributeValue", action = "http://services.pim.avaya.com/AgentAPI/UpdateAgentAttributeValue")
    @RequestWrapper(localName = "UpdateAgentAttributeValue", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.UpdateAgentAttributeValue")
    @ResponseWrapper(localName = "UpdateAgentAttributeValueResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.UpdateAgentAttributeValueResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public int updateAgentAttributeValue(
        @WebParam(name = "JobId", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        int jobId,
        @WebParam(name = "AgentId", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String agentId,
        @WebParam(name = "AttributeName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String attributeName,
        @WebParam(name = "AttributeValue", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        double attributeValue,
        @WebParam(name = "Operation", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        com.avaya.pim.services.pomagentapiservice.OperationType operation
    ) throws UpdateAgentAttributeValueFault;

    @WebMethod(operationName = "UpdateContactAttributeValueToList", action = "http://services.pim.avaya.com/AgentAPI/UpdateContactAttributeValueToList")
    @RequestWrapper(localName = "UpdateContactAttributeValueToList", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.UpdateContactAttributeValueToList")
    @ResponseWrapper(localName = "UpdateContactAttributeValueToListResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.UpdateContactAttributeValueToListResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public int updateContactAttributeValueToList(
        @WebParam(name = "ContactID", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactID,
        @WebParam(name = "ContactListName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String contactListName,
        @WebParam(name = "AttributeName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String attributeName,
        @WebParam(name = "AttributeValue", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String attributeValue
    ) throws UpdateContactAttributeValueToListFault;

    @WebMethod(operationName = "GetCampaignAttributesList", action = "http://services.pim.avaya.com/AgentAPI/GetCampaignAttributesList")
    @RequestWrapper(localName = "GetCampaignAttributesList", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetCampaignAttributesList")
    @ResponseWrapper(localName = "GetCampaignAttributesListResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.GetCampaignAttributesListResponse")
    @WebResult(name = "campaignAttributes", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public java.util.List<com.avaya.pim.services.pomagentapiservice.AttributeType> getCampaignAttributesList() throws GetCampaignAttributesListFault;

    @WebMethod(operationName = "RemoveFromDNCList", action = "http://services.pim.avaya.com/AgentAPI/RemoveFromDNCList")
    @RequestWrapper(localName = "RemoveFromDNCList", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.RemoveFromDNCList")
    @ResponseWrapper(localName = "RemoveFromDNCListResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.RemoveFromDNCListResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public boolean removeFromDNCList(
        @WebParam(name = "Address", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String address,
        @WebParam(name = "OrgName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String orgName,
        @WebParam(name = "CheckForRejectPattern", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.Boolean checkForRejectPattern,
        @WebParam(name = "CheckForPhoneFormatsRule", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.Boolean checkForPhoneFormatsRule
    ) throws RemoveFromDNCListFault;

    @WebMethod(operationName = "UpdateCampaignAttributeValue", action = "http://services.pim.avaya.com/AgentAPI/UpdateCampaignAttributeValue")
    @RequestWrapper(localName = "UpdateCampaignAttributeValue", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.UpdateCampaignAttributeValue")
    @ResponseWrapper(localName = "UpdateCampaignAttributeValueResponse", targetNamespace = "http://services.pim.avaya.com/AgentAPI/", className = "com.avaya.pim.services.pomagentapiservice.UpdateCampaignAttributeValueResponse")
    @WebResult(name = "Result", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
    public int updateCampaignAttributeValue(
        @WebParam(name = "JobId", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        int jobId,
        @WebParam(name = "AttributeName", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        java.lang.String attributeName,
        @WebParam(name = "AttributeValue", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        double attributeValue,
        @WebParam(name = "Operation", targetNamespace = "http://services.pim.avaya.com/AgentAPI/")
        com.avaya.pim.services.pomagentapiservice.OperationType operation
    ) throws UpdateCampaignAttributeValueFault;
}
